import { existsSync, readFileSync } from "fs";
import { join } from "path";
import { parse } from "yaml";

const DEFAULT_CONFIG_PATH = join(
  import.meta.dirname!,
  "..",
  "generate_conf.yaml",
);

export type GenerateSortBy = "median2weeks" | "reviews" | "name";
export type GenerateSortDirection = "asc" | "desc";

export interface TitleSteamSpyStats {
  appid: number;
  name: string;
  reviews: number;
  median2weeks: number;
}

interface GenerateConfYaml {
  sort?: unknown;
}

interface SortYamlBlock {
  by?: unknown;
  direction?: unknown;
}

const SORT_BY_VALUES = new Set<GenerateSortBy>([
  "median2weeks",
  "reviews",
  "name",
]);

function parseSortBy(raw: unknown): GenerateSortBy | undefined {
  if (raw === undefined || raw === null) return undefined;
  if (typeof raw !== "string") return undefined;
  if (SORT_BY_VALUES.has(raw as GenerateSortBy)) return raw as GenerateSortBy;
  return undefined;
}

function parseSortDirection(raw: unknown): GenerateSortDirection | undefined {
  if (raw === undefined || raw === null) return undefined;
  if (raw !== "asc" && raw !== "desc") return undefined;
  return raw;
}

function defaultSortDirection(by: GenerateSortBy): GenerateSortDirection {
  return by === "name" ? "asc" : "desc";
}

/** Reads optional top-level `sort` from `generate_conf.yaml`. */
export function loadSortConfig(
  filePath: string = DEFAULT_CONFIG_PATH,
): { sortBy: GenerateSortBy; sortDirection: GenerateSortDirection } {
  if (!existsSync(filePath)) {
    return {
      sortBy: "median2weeks",
      sortDirection: "desc",
    };
  }
  const doc = parse(readFileSync(filePath, "utf8")) as GenerateConfYaml;
  const raw = doc.sort;
  const defaults = {
    sortBy: "median2weeks" as GenerateSortBy,
    sortDirection: "desc" as GenerateSortDirection,
  };
  if (raw === undefined || raw === null) return defaults;

  if (typeof raw === "string") {
    const parsed = parseSortBy(raw);
    const sortBy = parsed ?? "median2weeks";
    if (parsed === undefined) {
      console.warn(
        `sort: invalid value ${JSON.stringify(raw)}, using median2weeks`,
      );
    }
    return {
      sortBy,
      sortDirection: defaultSortDirection(sortBy),
    };
  }

  if (typeof raw !== "object" || Array.isArray(raw)) return defaults;

  const o = raw as SortYamlBlock;
  let sortBy = parseSortBy(o.by) ?? "median2weeks";
  if (o.by !== undefined && o.by !== null && parseSortBy(o.by) === undefined) {
    console.warn(
      `sort.by: invalid value ${JSON.stringify(o.by)}, using median2weeks`,
    );
    sortBy = "median2weeks";
  }
  const dirFromYaml = parseSortDirection(o.direction);
  if (
    o.direction !== undefined &&
    o.direction !== null &&
    dirFromYaml === undefined
  ) {
    console.warn(
      `sort.direction: invalid value ${JSON.stringify(o.direction)}, using ${defaultSortDirection(sortBy)}`,
    );
  }
  const sortDirection = dirFromYaml ?? defaultSortDirection(sortBy);
  return { sortBy, sortDirection };
}

/** In-memory sort matching `generate` / `generate_conf.yaml` `sort` (Autogenerated, Overridden, Not in upstream). */
export function sortTitleStats(
  rows: TitleSteamSpyStats[],
  sortBy: GenerateSortBy,
  sortDirection: GenerateSortDirection,
): TitleSteamSpyStats[] {
  return [...rows].sort((a, b) => {
    if (sortBy === "name") {
      const c = a.name.localeCompare(b.name, undefined, { sensitivity: "base" });
      return sortDirection === "asc" ? c : -c;
    }
    const av = sortBy === "reviews" ? a.reviews : a.median2weeks;
    const bv = sortBy === "reviews" ? b.reviews : b.median2weeks;
    return sortDirection === "asc" ? av - bv : bv - av;
  });
}
