import { existsSync, readFileSync } from "fs";
import { parse } from "yaml";
import type { FilterId } from "./generate_filters";
import { isKnownFilterId } from "./generate_filters";

export type OverridesMap = Map<number, string[]>;

export interface OutputFlags {
  autogenerated: boolean;
  overrides: boolean;
  missing: boolean;
  noAutomaticRules: boolean;
}

export const DEFAULT_OUTPUT_FLAGS: OutputFlags = {
  autogenerated: true,
  overrides: true,
  missing: true,
  noAutomaticRules: true,
};

export interface GenerateConf {
  filters: Set<FilterId>;
  overrides: OverridesMap;
  output: OutputFlags;
  /** Appids that skip manifest-based autogen (use launch options / overrides only). */
  proven: Set<number>;
  /** Max manifest-sourced basenames per platform (by size desc). */
  manifestTopK: number;
  /** Case-insensitive regex strings; if basename matches any, drop for manifest picks. */
  manifestExcludePatterns: RegExp[];
}

interface YamlDoc {
  filters?: unknown;
  overrides?: unknown;
  output?: unknown;
  proven?: unknown;
  manifest_top_k?: unknown;
  manifest_exclude_patterns?: unknown;
}

function parseOutputFlags(raw: unknown): OutputFlags {
  if (
    raw === undefined ||
    raw === null ||
    typeof raw !== "object" ||
    Array.isArray(raw)
  ) {
    return { ...DEFAULT_OUTPUT_FLAGS };
  }
  const o = raw as Record<string, unknown>;
  return {
    autogenerated:
      typeof o.autogenerated === "boolean"
        ? o.autogenerated
        : DEFAULT_OUTPUT_FLAGS.autogenerated,
    overrides:
      typeof o.overrides === "boolean"
        ? o.overrides
        : DEFAULT_OUTPUT_FLAGS.overrides,
    missing:
      typeof o.missing === "boolean" ? o.missing : DEFAULT_OUTPUT_FLAGS.missing,
    noAutomaticRules:
      typeof o.noAutomaticRules === "boolean"
        ? o.noAutomaticRules
        : DEFAULT_OUTPUT_FLAGS.noAutomaticRules,
  };
}

export function loadGenerateConf(path: string): GenerateConf {
  const doc = parse(readFileSync(path, "utf8")) as YamlDoc;

  const filters = new Set<FilterId>();
  const fl = Array.isArray(doc.filters) ? doc.filters : [];
  for (const entry of fl) {
    if (typeof entry !== "string") {
      console.warn("generate_conf: skip non-string filter entry");
      continue;
    }
    if (!isKnownFilterId(entry)) {
      console.warn(`generate_conf: unknown filter "${entry}", ignoring`);
      continue;
    }
    filters.add(entry);
  }

  const overrides: OverridesMap = new Map();
  if (doc.overrides && typeof doc.overrides === "object" && !Array.isArray(doc.overrides)) {
    for (const [key, value] of Object.entries(doc.overrides as Record<string, unknown>)) {
      const appid = parseInt(String(key), 10);
      if (Number.isNaN(appid)) {
        console.warn(`generate_conf: overrides: skip non-numeric app id "${key}"`);
        continue;
      }
      if (!Array.isArray(value)) {
        console.warn(`generate_conf: overrides[${appid}]: expected array, skipping`);
        continue;
      }
      const names = value.filter((x): x is string => typeof x === "string" && x.length > 0);
      if (names.length > 0) overrides.set(appid, names);
    }
  }

  const output = parseOutputFlags(doc.output);

  const proven = new Set<number>();
  if (Array.isArray(doc.proven)) {
    for (const x of doc.proven) {
      const id = typeof x === "number" ? x : parseInt(String(x), 10);
      if (Number.isFinite(id)) proven.add(id);
    }
  }

  let manifestTopK = 3;
  if (doc.manifest_top_k !== undefined && doc.manifest_top_k !== null) {
    const k = typeof doc.manifest_top_k === "number" ? doc.manifest_top_k : parseInt(String(doc.manifest_top_k), 10);
    if (Number.isFinite(k) && k >= 1) manifestTopK = Math.min(32, k);
  }

  const manifestExcludePatterns: RegExp[] = [];
  if (Array.isArray(doc.manifest_exclude_patterns)) {
    for (const s of doc.manifest_exclude_patterns) {
      if (typeof s !== "string" || !s.length) continue;
      try {
        manifestExcludePatterns.push(new RegExp(s, "i"));
      } catch {
        console.warn(`yaml_conf: invalid manifest_exclude_patterns regex, skipping: ${s}`);
      }
    }
  }

  return {
    filters,
    overrides,
    output,
    proven,
    manifestTopK,
    manifestExcludePatterns,
  };
}

export function tryLoadGenerateConf(defaultPath: string): GenerateConf | null {
  if (!existsSync(defaultPath)) return null;
  return loadGenerateConf(defaultPath);
}
